name: stastic web to s3
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: send to s3
        uses: actions/checkout@v4
      - name: config aws cli
        uses: aws-actions/configure-aws-credentials@v4
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} }}
          WS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
